networks:
  local_beach:
    external: true

services:
  webserver:
    image: flownative/localbeach-nginx-proxy:0.4.1
    container_name: local_beach_nginx
    networks:
      - local_beach
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - {{certificatesPath}}:/etc/nginx/certs
    environment:
      - DEFAULT_HOST=hello.localbeach.net
  database:
    image: mariadb:10.11
    container_name: local_beach_database
    user: 501:20
    networks:
      - local_beach
    volumes:
      - {{databasePath}}:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
       - 3307:3306
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
