networks:
  local_beach:
    external: true

services:
  database:
    image: mysql:8
    container_name: local_beach_database
    networks:
      - local_beach
    volumes:
      - {{mysqlDatabasePath}}:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  mariadb:
    image: mariadb:10.11
    container_name: local_beach_mariadb
    networks:
      - local_beach
    volumes:
      - {{mariadbDatabasePath}}:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
